//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobzzService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public int id { get; set; }
        public string level_name { get; set; }
    }
}
